### ISSUE TITLE
Use jekyll, maybe?

### ISSUE THREAD

**Issue by utkarsh2102** [dupr/dupr.github.io#1]
Setting up a Jekyll website would be easy and is readily supported by GitHub as well.  
Also, it'd be easier to write documents and blogs as Markdown is fully supported.  
On the contrary, plain HTML would be hard for contributors to chip in, in the field of documentation, etc. Markdown is always preferable, no?

**Comment by cdluminate** [comment]
@utkarsh2102 Github's web page generator (Jekyll) is the first choice in my mind, as it only requires the minimum effort. Will look into this later.

**Comment by utkarsh2102** [comment]
@cdluminate, this was what I was suggesting :)  
The only thing effort required is to decide on a theme :P

**Comment by cdluminate** [comment]
@utkarsh2102 Then I ... used bootstrap ... and pandoc ...
